object_tracking_config:
  clip_model: "ViT-L/14"
  clip_batch: 16
  clip_classes:
    - "person"
    - "child"
    - "group of people"
    - "crowd"
    - "squirrel"
    - "monkey"
    - "animal"
    - "dog"
    - "cat"
    - "horse"
    - "cow"
    - "bird"
    - "camel"
    - "monkey"
    - "tiger"
    - "rabbit"
    - "bunny"
    - "squirrel"
    - "fox"
    - "bear"
    - "drum"
    - "trumpet"
    - "banner"
    - "flag"
    - "confetti"
    - "guard"
    - "carpet"
    - "throne"
    - "palace"
    - "market"
    - "car"
    - "truck"
    - "bus"
    - "motorcycle"
    - "bicycle"
    - "airplane"
    - "boat"
    - "chair"
    - "table"
    - "sofa"
    - "bed"
    - "lamp"
    - "bag"
    - "backpack"
    - "bottle"
    - "cup"
    - "umbrella"
    - "book"
    - "suitcase"
    - "phone"
    - "camera"
    - "laptop"
    - "screen"
    - "microphone"
    - "food"
    - "drink"
    - "fruit"
    - "vegetable"
    - "apple"
    - "tree"
    - "plant"
    - "flower"
    - "grass"
    - "rock"
    - "mountain"
    - "river"
    - "lake"
    - "ocean"
    - "forest"
    - "bush"
    - "log"
    - "leaf"
    - "mushroom"
    - "building"
    - "house"
    - "bridge"
    - "road"
    - "tower"
    - "castle"
    - "clothing"
    - "hat"
    - "helmet"
    - "uniform"
    - "armor"
    - "object"
    - "unknown"
    - "background"

  generic_labels:
    - "animal"
    - "object"
    - "unknown"
    - "thing"

attribute_enrichment:
  prefer_saved_crop: true

  attribute_presets:
    - parade
    - nature
    - fashion

  extra_attributes: []

  templates:
    - "a photo of a {attr} object"
    - "the object is {attr}"
    - "a {attr} thing"
    - "this looks {attr}"
    - "an object that is {attr}"

  clip_model: "ViT-L/14"
  batch_size: 16

  presets:
    parade:
      - "red"
      - "blue"
      - "green"
      - "yellow"
      - "black"
      - "white"
      - "brown"
      - "gray"
      - "gold"
      - "silver"
      - "purple"
      - "pink"
      - "silk"
      - "velvet"
      - "satin"
      - "leather"
      - "metal"
      - "glass"
      - "fabric"
      - "wooden"
      - "plastic"
      - "ornate"
      - "embroidered"
      - "striped"
      - "floral"
      - "polished"
      - "glittering"
      - "sparkling"
      - "royal"
      - "ceremonial"
      - "festive"
      - "decorated"
      - "shiny"
      - "bright"
      - "colorful"
      - "massive"
      - "tall"
      - "wide"
      - "long"
      - "crowded"
      - "dense"

    nature:
      - "green"
      - "brown"
      - "gray"
      - "white"
      - "black"
      - "leafy"
      - "floral"
      - "rocky"
      - "sandy"
      - "muddy"
      - "grassy"
      - "wooden"
      - "wet"
      - "dry"
      - "snowy"
      - "sunlit"
      - "shadowed"
      - "natural"
      - "wild"

    fashion:
      - "red"
      - "blue"
      - "black"
      - "white"
      - "gold"
      - "silver"
      - "pink"
      - "purple"
      - "silk"
      - "velvet"
      - "denim"
      - "cotton"
      - "leather"
      - "lace"
      - "striped"
      - "polka dot"
      - "plaid"
      - "floral"
      - "plain"
      - "formal"
      - "casual"
      - "elegant"
      - "ornate"

    vehicles:
      - "red"
      - "blue"
      - "black"
      - "white"
      - "silver"
      - "yellow"
      - "metal"
      - "polished"
      - "shiny"
      - "matte"
      - "fast"
      - "large"
      - "small"
      - "wheeled"

    generic:
      - "red"
      - "blue"
      - "green"
      - "yellow"
      - "black"
      - "white"
      - "brown"
      - "gray"
      - "wooden"
      - "metal"
      - "plastic"
      - "leather"
      - "glass"
      - "fabric"
      - "striped"
      - "polka dot"
      - "plaid"
      - "floral"
      - "plain"
      - "small"
      - "large"
      - "bright"
      - "dark"
      - "clean"
      - "dirty"
      - "old"
      - "new"

  core_attributes:
    - "red"
    - "blue"
    - "green"
    - "yellow"
    - "black"
    - "white"
    - "brown"
    - "gray"
    - "wooden"
    - "metal"
    - "plastic"
    - "leather"
    - "glass"
    - "fabric"
    - "striped"
    - "floral"
    - "plain"
    - "small"
    - "large"
    - "bright"
    - "dark"
    - "ornate"
    - "shiny"
    - "colorful"